### ISSUE TITLE
Segmentation fault in code commit 1.12.0-121-g44a526a

### ISSUE THREAD

**Issue by Andlui9** [accel-ppp/accel-ppp#12]
I am using version 1.12.0-121-g44a526a of the code available on github and the following problem happens:

```
Starting program: /usr/sbin/accel-pppd -c /etc/accel-ppp/accel-ppp.conf -p /var/run/accel-ppp.pid
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff48f5700 (LWP 62905)]
[New Thread 0x7ffff40f4700 (LWP 62906)]
[New Thread 0x7ffff38f3700 (LWP 62907)]
[New Thread 0x7ffff7fc4700 (LWP 62908)]
[New Thread 0x7ffff30f2700 (LWP 62909)]
[New Thread 0x7ffff2ff1700 (LWP 62910)]
[New Thread 0x7ffff2ef0700 (LWP 62911)]
[New Thread 0x7ffff2def700 (LWP 62912)]
[New Thread 0x7ffff2cee700 (LWP 62913)]
[New Thread 0x7ffff2bed700 (LWP 62914)]
[New Thread 0x7ffff2aec700 (LWP 62915)]
[New Thread 0x7ffff29eb700 (LWP 62916)]
[New Thread 0x7ffff21ea700 (LWP 62917)]

Thread 11 "accel-pppd" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff2bed700 (LWP 62914)]
0x00007ffff6268c3b in rad_auth_finalize (rpd=0x7fffe80076b8, r=1) at /usr/local/src/accel/accel-ppp/accel-pppd/radius/auth.c:157
157			rad_req_free(rpd->auth_ctx->req);
(gdb) bt full
#0  0x00007ffff6268c3b in rad_auth_finalize (rpd=0x7fffe80076b8, r=1) at /usr/local/src/accel/accel-ppp/accel-pppd/radius/auth.c:157
No locals.
#1  0x00007ffff6268e02 in rad_auth_recv (req=0x7fffe80305f8) at /usr/local/src/accel/accel-ppp/accel-pppd/radius/auth.c:189
        pack = 0x7fffe8043eb8
        dt = 1000
#2  0x00007ffff6266300 in rad_req_read (h=0x7fffe8030608) at /usr/local/src/accel/accel-ppp/accel-pppd/radius/req.c:433
        req = 0x7fffe80305f8
        pack = 0x7fffe8043eb8
#3  0x00007ffff7bd267d in ctx_thread (ctx=0x7fffe8006a88) at /usr/local/src/accel/accel-ppp/accel-pppd/triton/triton.c:252
        h = 0x7fffe8031de8
        t = 0x7ffff667f15c <pppoe_conn_ctx_switch>
        call = 0x7ffff2becd30
        tt = 140737085728584
        events = 1
#4  0x00007ffff7bd2438 in triton_thread (thread=0x555556a92b30) at /usr/local/src/accel/accel-ppp/accel-pppd/triton/triton.c:192
        set = {__val = {516, 0 <repeats 15 times>}}
        sig = 10
        need_free = 0
        stack = 0x0
#5  0x00007ffff77b04a4 in start_thread (arg=0x7ffff2bed700) at pthread_create.c:456
        __res = <optimized out>
        pd = 0x7ffff2bed700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737265981184, 2718206135543199681, 140737488347662, 140737488347663, 140737264930816, 3, 
                -2718230884689446975, -2718224869269637183}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, 
              canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#6  0x00007ffff6975d0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
No locals.
(gdb) quit
A debugging session is active.

	Inferior 1 [process 62901] will be killed.

Quit anyway? (y or n) y

```

The behavior is more or less as follows, I turn on the process and right when the pppoe users start to connect, the problem happens, and the process restarts, and it stays forever if I don't kill it

**Comment by Andlui9** [comment]
Hi, my conf like this:

```
[modules]
pppoe
radius
ippool
shaper
log_file
ipv6_nd
ipv6pool
ipv6_dhcp
auth_pap
pppd_compat


[core]
thread-count=8
log-error=/var/log/accel-ppp/core.log

[common]
verbose=1
sid-case=lower
single-session=replace
sid-source=urandom

[auth]
verbose=1
noauth=0
any-login=0



[ppp]
verbose=1
ccp=0
mtu=1480
max-mtu=1492
min-mtu=1452
max-mru=1492
mppe=deny
pcomp=deny
check-ip=1
accomp=deny
sid-case=lower
unit-cache=0
unit-preallocate=1
lcp-echo-timeout=30
lcp-echo-interval=5
single-session=replace
ipv4=require
ipv6=prefer
ipv6-intf-id=0:0:0:1
ipv6-peer-intf-id=0:0:0:2
ipv6-accept-peer-intf-id=1

[pppoe]
verbose=1
mppe=deny
ip-pool=pool-1-pppoe
ac-name=nas.1
service-name=nas.1
accept-any-service=1
called-sid=ifname
sid-uppercase=1
ifname-in-sid=called-sid
mac-filter=/etc/accel-ppp/mac-blacklist,deny
pado-delay=0,10:1000,20:1200,30:1500,40:1800,50:2000,60:2100,70:2300
vlan-timeout=604800
vlan-name=%I.%N

interface=ens1f1

vlan-mon=ens1f0.3921,1100-1101
interface=re:ens1f0.3921\.([1-9]|[1-9][0-9]|[1-9][0-9][0-9]|[1-9][0-9][0-9][0-9])

vlan-mon=ens1f0,3900-3920,3922-4094
interface=re:ens1f0\.([1-9]|[1-9][0-9]|[1-9][0-9][0-9]|[1-9][0-9][0-9][0-9])

vlan-mon=eno2,501-504,1950-1999,2050-2199,2950-2999,2250-2300,2800-2850
interface=re:eno2\.([1-9]|[1-9][0-9]|[1-9][0-9][0-9]|[1-9][0-9][0-9][0-9])

[dns]
dns1=fr.st.240.7
dns2=fr.st.240.8

[radius]
verbose=1
timeout=2
max-try=0
sid_in_auth=1
acct-timeout=0
interim-verbose=0
nas-identifier=nas-1
acct-interim-interval=900
gw-ip-address=fr.st.240.11
nas-ip-address=fr.st.240.11
dae-server=0.0.0.0:3799,my_secret
dictionary=/usr/share/accel-ppp/radius/dictionary
server=fr.st.240.3,my_secret,auth-port=1812,acct-port=0,req-limit=0,fail-timeout=0
server=fr.st.240.4,my_secret,auth-port=0,acct-port=1813,req-limit=0,fail-timeout=0

[client-ip-range]
disable

[ip-pool]
verbose=1
shuffle=1
attr=Framed-Pool
gw-ip-address=fr.st.240.11

100.101.32.0/20,name=pool-1-pppoe
100.101.48.0/20,name=pool-1-pppoe

198.18.4.2-254,name=overdue
198.18.5.2-254,name=overdue

[ipv6-dns]
abcd:cdef:2::7
abcd:cdef:2::8

[ipv6-nd]
AdvAutonomousFlag=1

[ipv6-pool]
attr-prefix=Delegated-IPv6-Prefix-Pool
attr-address=Stateful-IPv6-Address-Pool

abcd:cdef:a001::/48,64
delegate=abcd:cdef:a020::/43,56

fc00:3558:a001::/48,64,name=pppoe-v6-deny-link
delegate=fc00:3558:a020::/43,56,name=pppoe-v6-deny-pfx

[ipv6-dhcp]
verbose=1
pref-lifetime=7200
valid-lifetime=10800
route-via-gw=1

[log]
copy=1
color=1
level=2
log-debug=/var/log/accel-ppp/debug.log
log-file=/var/log/accel-ppp/accel-ppp.log
log-emerg=/var/log/accel-ppp/emerg.log
log-fail-file=/var/log/accel-ppp/auth-fail.log

[pppd-compat]
verbose=1
radattr-prefix=/var/run/radattr
ip-up=/usr/local/bin/pppoe-up.sh
ip-down=/usr/local/bin/pppoe-down.sh
ip-change=/usr/local/bin/pppoe-change.sh

[shaper]
verbose=1
attr=Filter-Id
up-limiter=police
down-limiter=tbf
moderate-quantum=1
time-range=1,01:00-08:00

[cli]
verbose=0
prompt=accel-pppoe
tcp=0.0.0.0:2001
telnet=0.0.0.0:2000
sessions-columns=ifname,username,ip,rate-limit,called-sid,calling-sid,tx-bytes,rx-bytes,state,uptime
```

**Comment by anphsw** [comment]
Please revert 44a526ab7de382f2ea0295c88a6024960cabca77 and test again.

**Comment by Andlui9** [comment]
> Please revert [44a526a](https://github.com/accel-ppp/accel-ppp/commit/44a526ab7de382f2ea0295c88a6024960cabca77) and test again.

this is precisely the version that is presenting the problem.

**Comment by anphsw** [comment]
Please also try 5d19767d240114b4915f3b555365f9dc08400cc5 that is already in PR.

**Comment by DmitriyEshenko** [comment]
Hello, @Andlui9 do you have any updates with the latest patches from the master branch?

**Comment by DmitriyEshenko** [comment]
Looks like described issue is resolved.
